name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Fix Gradle project
        run: |
          flutter clean
          rm -rf android ios  # Elimina las carpetas de plataforma existentes
          flutter create --platforms android .  # Regenera la estructura del proyecto
          cp -r lib/ tmp_lib/  # Respalda tu código
          flutter create --platforms android .
          rm -rf lib/
          mv tmp_lib/ lib/
          
      - run: flutter pub get
      - run: flutter build apk --release
      
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
