name: Build APK
on: [push]  # Se ejecuta al hacer push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest  # Máquina virtual con Ubuntu

    steps:
      # 1. Descarga el código del repositorio
      - uses: actions/checkout@v4

      # 2. Configura Flutter (versión estable)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      # 3. Obtiene las dependencias del proyecto
      - run: flutter pub get

      # 4. Genera el APK en modo release
      - run: flutter build apk --release

      # 5. Sube el APK como artefacto (usa @v4)
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk  # Nombre del archivo
          path: build/app/outputs/flutter-apk/app-release.apk  # Ruta del APK
